name: Deploy Reports

on:
  push:
    branches:
      - main
    paths:
      - 'reports/**'

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Copy reports to server_local
        run: |
          mkdir -p /opt/reports
          rsync -av PLD/ /opt/reports/

